// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Vb1fVj_eneWibQYxrg4mwtBrtZXKYGQ',
    appId: '1:171386166486:web:9bec247199a2cced37bd77',
    messagingSenderId: '171386166486',
    projectId: 'speakit-startup',
    authDomain: 'speakit-startup.firebaseapp.com',
    storageBucket: 'speakit-startup.appspot.com',
    measurementId: 'G-YYZ9C03GJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Ne__ljRc5Nq8jsHWyi6kDoJySTzbcFs',
    appId: '1:171386166486:android:543a15d99dda366237bd77',
    messagingSenderId: '171386166486',
    projectId: 'speakit-startup',
    storageBucket: 'speakit-startup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc7wkbpyIrx76LWKCfS3RlFMZntcfRmZ0',
    appId: '1:171386166486:ios:5293a452e9f2230f37bd77',
    messagingSenderId: '171386166486',
    projectId: 'speakit-startup',
    storageBucket: 'speakit-startup.appspot.com',
    iosClientId: '171386166486-3i49kku1bpoj5slakcfqb1ijvi9q79t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.speakMobile',
  );
}
